### ISSUE TITLE
`from_bash` depends on particular tools being available in docker image

### ISSUE THREAD

**Issue by ghost** [sbg/sevenbridges-cwl#1]
The `from_bash` function is my most intensively used function in `sbg-cwl`. It however does not work when the docker image does not have certain tools. For example `alpine` which is a lightweight distribution I use for testing can not be used.

Importantly, I have existing docker images from existing tools which I can not use because they do not contain the special utilities required by this function.

It would be nice to recast the `from_bash` mechanism such that it does not depend on any special  utilities, for example, by invoking CWL's `create file` feature.

Thanks!

**Comment by filiptubic** [comment]
The `from_bash` function was never designed to work out of the box with some stock, minimal docker image like `alpine`. This particular docker image doesn't have `bash` inside whatsoever. And of course, you need to install all runtime dependencies inside it, specified in the quickstart. 

I will close the issue if that's ok.
