### ISSUE TITLE
`get_metadata()` function generates spurious "\r" on windows platforms

### ISSUE THREAD

**Issue by ghost** [sbg/sevenbridges-cwl#2]
On windows platforms the `get_metadata()` function seems to insert `\r` characters, this makes CWL created on windows unusable.

Thanks!

**Comment by filiptubic** [comment]
Hey @kaushik-work , can you place here some simple code example that demonstrates this issue? I assume you are creating a tool from bash code.

EDIT:
My code completes successfully on Windows 10 (run tested using `cwltool`):

```
from sbg import cwl

t = cwl.from_bash(
    'echo "$(get_metadata in_file sample_id)"',
    docker='demo'
)
t.dump('tool.cwl')
```

**Comment by filiptubic** [comment]
Hey @kaushik-work  should I close this issue?

**Comment by ghost** [comment]
@filiptubic yes please just close it - if I can replicate, I'll reopen. Thanks!
