### ISSUE TITLE
Some documentation requests

### ISSUE THREAD

**Issue by ghost** [sbg/sevenbridges-cwl#3]
Hi @filiptubic !

All these examples are awesome! Two requests for documentation.

1. Create a list of requirements that the docker image should have (like `Python`, `dill` and `pyYAML`)
1. I wonder if we could have an example for a Python tool that globs a file?

Thanks!

**Comment by filiptubic** [comment]
Hi @kaushik-work,

1) Docker image requirements are already in the description in quickstart in **Docker image preparation** section.
2) We already have example which globs a file: https://github.com/sbg/sevenbridges-cwl/blob/master/docs/examples/gc%20content/gc_content.py#L10

**Comment by ghost** [comment]
Nice! Could we please link to the docs from the Readme. I know it is common practice to browse the docs from github, rather than clone and build the docs. Thanks!
