### ISSUE TITLE
Hosted package documentation

### ISSUE THREAD

**Issue by nanxstats** [sbg/sevenbridges-cwl#6]
"If something isn't on the web, it doesn't exist at all."

Instead of making users install extra dependencies to build the docs locally, would it be nice if we host the package docs online (readthedocs or github pages) and link the url in the repo description section/in the readme, so people can read them directly?

That's what we did for [sevenbridges-r](https://sbg.github.io/sevenbridges-r/).

@kaushik-work @filiptubic

**Comment by filiptubic** [comment]
Documentation is now hosted online [here](https://sevenbridges-cwl.readthedocs.io).

**Comment by mattions** [comment]
@filiptubic could you add the read_the_docs tag on the README as well?
It's a classic way for people to find the docs.

**Comment by nanxstats** [comment]
-wow, this looks great! Thank you! 👍
